version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_DB: kafka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654321
    ports:
      - "5432:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "person-topic:1:3"